---
sidebar: sidebar 
permalink: task_install_deploy.html 
keywords: install, installing, ontap select deploy, deploy administration utility, deploy utility 
summary: 您需要安装 ONTAP Select Deploy 管理实用程序并使用该实用程序创建 ONTAP Select 集群。 
---
= 安装 ONTAP Select Deploy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您需要安装 ONTAP Select Deploy 管理实用程序并使用该实用程序创建 ONTAP Select 集群。



== 下载虚拟机映像

您可以从 NetApp 支持站点下载 ONTAP Select 软件包。

.开始之前
https://mysupport.netapp.com/site/user/registration["您已注册NetApp支持站点帐户"^](英文)

.关于此任务
ONTAP Select Deploy 管理实用程序打包为基于开放虚拟化格式 (OVF) 标准的虚拟机 (VM)。单个压缩文件具有后缀 `ova`。VM 为 ONTAP Select 节点提供 Deploy 服务器和安装映像。

.步骤
. 使用 Web 浏览器访问 link:https://mysupport.netapp.com/site/["NetApp 支持站点"^] 并登录。
. 从菜单中选择 *Downloads*，然后从下拉菜单中选择 *Downloads*。
. 在"下载"页面上的"所有产品 A-Z"下，选择字母 *O*。
. 向下滚动并选择 *ONTAP Select*。
. 选择所需的软件包版本。
. 查看最终用户许可协议(EULA),并选择*Accept & Continue*。
. 选择并下载相应的软件包，根据需要响应所有提示。




== 验证 ONTAP Select Deploy OVA 签名

在安装安装包之前，应验证 ONTAP Select Open Virtualization Appliance (OVA) 签名。

.开始之前
验证您的系统是否满足以下要求：

* 用于基本验证的OpenSSL版本1.0.2至3.0
* 可通过公共互联网访问联机证书状态协议(Online Certificate Status Protocol、OCSP)验证


.步骤
. 从 NetApp 支持站点的产品下载页面获取以下文件：
+
[cols="2*"]
|===
| 文件 | 说明 


| `ONTAP-Select-Deploy-Production.pub` | 用于验证签名的公共密钥。 


| `csc-prod-chain-ONTAP-Select-Deploy.pem` | 公共证书颁发机构(CA)的信任链。 


| `csc-prod-ONTAP-Select-Deploy.pem` | 用于生成密钥的证书。 


| `ONTAPdeploy.ova` | ONTAP Select的产品安装可执行文件。 


| `ONTAPdeploy.ova.sig` | SHA-256算法经过哈希处理、然后由远程支持代理(RSA)使用安装程序的密钥和签名进行 `csc-prod`签名。 
|===
. 验证此文件是否 `ONTAPdeploy.ova.sig`正在使用关联的证书和验证命令。
. 使用以下命令验证签名：
+
[listing]
----
openssl dgst  -sha256 -verify ONTAP-Select-Deploy-Production.pub -signature ONTAPdeploy.ova.sig  ONTAPdeploy.ova
----




== 部署虚拟机

必须使用 OVF VM 映像安装并启动 ONTAP Select Deploy VM。作为安装过程的一部分，您可以将网络接口配置为使用 DHCP 或静态 IP 配置。

.开始之前
对于ESXi虚拟机管理程序、您必须准备部署ONTAP Select Deploy虚拟机：

* 通过安装 VMware Client Integration 插件或根据需要执行类似配置，在浏览器中启用 OVF 功能
* 如果要为Deploy虚拟机动态分配IP地址、请在VMware环境中启用DHCP


对于ESXi和KVM虚拟机管理程序、您必须知道创建虚拟机时要使用的配置信息、包括虚拟机名称、外部网络和主机名。定义静态网络配置时，需要以下追加信息 ：

* Deploy虚拟机的IP地址
* 网络掩码
* 网关（路由器）的 IP 地址
* 主 DNS 服务器的 IP 地址
* 第二个 DNS 服务器的 IP 地址
* DNS搜索域


.关于此任务
如果您使用的是 vSphere ，则 Deploy OVF 模板向导会提供一个表单，用于提供所有 Deploy 配置信息，包括网络配置。但是、如果您选择不使用此表单、则可以改用Deploy虚拟机的控制台来配置网络。

.步骤
您需要执行的步骤取决于您使用的是ESXi虚拟机管理程序还是KVM虚拟机管理程序。

[role="tabbed-block"]
====
.ESXi
--
. 访问 vSphere 客户端并登录。
. 导航到层次结构中的相应位置，然后选择 * 部署 OVF 模板 * 。
. 选择 OVA 文件并完成 Deploy OVF Template 向导，选择适合您的环境的选项。
+
您必须为管理员帐户定义密码。登录到 Deploy 实用程序时，需要提供此密码。

. 部署虚拟机后，根据您对部署向导的输入，选择新虚拟机并打开电源（如果尚未打开电源）。
. 如果需要、您可以使用VM控制台配置Deploy网络：
+
.. 单击 *Console* 选项卡以访问 ESXi 主机设置外壳并监控开机过程。
.. 等待出现以下提示：
+
主机名：

.. 键入主机名并按 * 输入 * 。
.. 等待出现以下提示：
+
提供管理员用户的密码：

.. 键入密码并按 * 输入 * 。
.. 等待出现以下提示：
+
是否使用 DHCP 设置网络信息？[N] ：

.. 键入*n*定义静态IP配置，或键入*y*使用DHCP，然后选择*Enter*。
.. 如果选择静态配置，请根据需要提供所有网络配置信息。




--
.KVM
--
. 在Linux服务器上登录到命令行界面：
+
[listing]
----
ssh root@<ip_address>
----
. 创建新目录并提取原始VM映像：
+
[listing]
----
mkdir /home/select_deploy25
cd /home/select_deploy25
mv /root/<file_name> .
tar -xzvf <file_name>
----
. 创建并启动运行Deploy管理实用程序的KVM VM：
+
[listing]
----
virt-install --name=select-deploy --vcpus=2 --ram=4096 --os-variant=debian10 --controller=scsi,model=virtio-scsi --disk path=/home/deploy/ONTAPdeploy.raw,device=disk,bus=scsi,format=raw --network "type=bridge,source=ontap-br,model=virtio,virtualport_type=openvswitch" --console=pty --import --noautoconsole
----
. 如果需要、您可以使用VM控制台配置Deploy网络：
+
.. 连接到VM控制台：
+
[listing]
----
virsh console <vm_name>
----
.. 等待出现以下提示：
+
[listing]
----
Host name :
----
.. 键入主机名并选择*Enter*。
.. 等待出现以下提示：
+
[listing]
----
Use DHCP to set networking information? [n]:
----
.. 键入*n*定义静态IP配置，或键入*y*使用DHCP，然后选择*Enter*。
.. 如果选择静态配置，请根据需要提供所有网络配置信息。




--
====


== Sign in 到部署 Web 界面

您应登录到 Web 用户界面，以确认部署实用程序可用并执行初始配置。

.步骤
. 使用 IP 地址或域名将浏览器指向 Deploy 实用程序：
+
`\https://<ip_address>/`

. 提供管理员（ admin ）帐户名称和密码并登录。
. 如果显示*欢迎使用ONTAP Select *弹出窗口，请查看前提条件并选择*OK*继续。
. 如果这是首次登录，而您未使用 vCenter 提供的向导安装 Deploy ，请在出现提示时提供以下配置信息：
+
** 管理员帐户的新密码（必需）
** AutoSupport （可选）
** 使用帐户凭据的 vCenter Server （可选）




.相关信息
link:task_cli_signing_in.html["使用SSH登录到Deploy"]
